services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile  # Dockerfile inside the client folder
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
